# Generated by Django 4.2.7 on 2023-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('ДИПЛ', 'Диплом'), ('ЗАЯВ', 'Заявление'), ('ПАСПОРТ', 'Паспорт'), ('ПИСЬМО', 'Письмо'), ('СВИД', 'Свидетельство'), ('СПРАВ', 'Справка')], default='СПРАВ', max_length=16, verbose_name='Тип документа'),
        ),
    ]
